name: Test Project

on:
  pull_request:
    branches:
      -main

jobs:
  test:
    runs-on: ubuntu-latest
    containers:
      image: node:20
    steps:
      - uses: actions/checkout@v3
        wtih:
          node-version: 20
      - run: npm ci
      - run: npm test
      - run: npm run build